### ISSUE TITLE
Running `./bin/gossamer init` fails

### ISSUE THREAD

**Issue by axaysagathiya** [ChainSafe/gossamer#2771] opened 2022-08-22 16:55 UTC
## Describe the bug

While trying to initialize Gossamer errors.

```
axay@axay-Inspiron-3542:~/go/src/github.com/ChainSafe/gossamer$ ./bin/gossamer init --force
2022-08-22T22:17:08+05:30 INFO     🕸️ initialising node with name asset-wine-3519, id gssmr_test, base path /home/axay/.gossamer/gssmr and genesis ./chain/gssmr/genesis-spec.json...	node.go:L128	pkg=dot
2022-08-22T22:17:08+05:30 ERROR    failed to initialise node: failed to convert genesis-spec to raw genesis: key array less than 2	main.go:L342	pkg=cmd
failed to convert genesis-spec to raw genesis: key array less than 2
```

## Expected Behavior

-

## Current Behavior

-

## Possible Solution

-

## To Reproduce
Steps to reproduce the behaviour:

1. 
2. 
3. 

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
</br>

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by kishansagathiya** [comment] 2022-08-23 07:29
duplicate of https://github.com/ChainSafe/gossamer/issues/2770

**Closed by kishansagathiya** 2022-08-23 07:29 UTC
Labels: Type: Bug
