### ISSUE TITLE
Flaky tests in `lib/runtime/wasmer/exports_test.go`

### ISSUE THREAD

**Issue by axaysagathiya** [ChainSafe/gossamer#3413] opened 2023-07-31 13:53 UTC
## Describe the bug

tests `TestInstance_ParachainHostCandidatePendingAvailability` and `TestInstance_ParachainHostSessionInfo` fail sometimes.

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
 --- FAIL: TestInstance_ParachainHostCandidatePendingAvailability (0.54s)
    exports_test.go:1421: 
        	Error Trace:	/home/runner/actions-runner/_work/gossamer/gossamer/lib/runtime/wasmer/test_helpers.go:55
        	            				/home/runner/actions-runner/_work/gossamer/gossamer/lib/runtime/wasmer/exports_test.go:1421
        	Error:      	Received unexpected error:
        	            	setting up VM: wasm decompression failed: corrupt stream, did not find end of stream
        	Test:       	TestInstance_ParachainHostCandidatePendingAvailability
--- FAIL: TestInstance_ParachainHostSessionInfo (0.69s)
    exports_test.go:1461: 
        	Error Trace:	/home/runner/actions-runner/_work/gossamer/gossamer/lib/runtime/wasmer/test_helpers.go:55
        	            				/home/runner/actions-runner/_work/gossamer/gossamer/lib/runtime/wasmer/exports_test.go:1461
        	Error:      	Received unexpected error:
        	            	setting up VM: wasm decompression failed: corrupt stream, did not find end of stream
        	Test:       	TestInstance_ParachainHostSessionInfo
  ```
</details> 
</br>

**Comment by edwardmack** [comment] 2023-09-25 08:20
I've run these tests (in lib/runtime/wazero/instance_test since the lib/runtime/wasmer has been removed)  multiple times trying to reproduce the error, but have not been able to.  I wonder if this bug was fixed by switching from wasmer to wazero?

**Comment by kishansagathiya** [comment] 2023-09-29 12:46
> I wonder if this bug was fixed by switching from wasmer to wazero?

Could be. Went through some recent CI jobs. didn't see it. Let's close this.

**Closed by kishansagathiya** 2023-09-29 12:46 UTC
Labels: Type: Bug, Parachain Host
