### ISSUE TITLE
create cross-client devnet and document issues

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1475] opened 2021-03-17 22:27 UTC
## Task summary

- we should spin up a devnet that has both gossamer and substrate nodes acting as authorities and document any issues that arise

**Comment by danforbes** [comment] 2022-01-05 17:25
Closing as duplicate of #1356, which I have updated with the `w3f approved` label and added #1393 as a blocker.

**Closed by danforbes** 2022-01-05 17:25 UTC
Labels: tests, p3, w3f approved
