### ISSUE TITLE
Pre-Runtime digest message format issue

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#838] opened 2020-05-02 15:38 UTC
## Expected Behavior
Calling chain RCP methods that return header with digest of type Pre-Runtime should be formatting as detailed in Defniniton 3.7 in Polkadot Host Protocol Specification.
Example from result when calling chain_getHeader on test substrate node: `0x0661757261202596c70f00000000`
``` 
byte 1       - 06 - Pre-Runtime type
byte 2 - 5   - 61757261 - Eid (aura)
byte 6       - 20 - Scale enc length byte array (8 bytes)
byte 7 - 14  - 2596c70f00000000 - The 8 byte array
```
## Current Behavior
Too many bytes are being included in Pre-Runtime digest message, example from gossamer: `0x064241424558f16c62c0cdea9bdb9b341227845a90516e8417eba2bc7c6cff39cd12120e212106e05aeca6ee2f40126a3edcf015a4a4bc9932aed7fef1257c114265184f0e1833b7c2b9be2656b0833f7060d7301d250c1041e1d949c3651f8fc74e25c90c00000000000000004f00000000000000`

```
byte 1       - 06 - Pre-Runtime type
byte 2 - 5   - 4241445 - Eid (BABE)
byte 6       - 58 - Scale enc length byte array (22 bytes)
byte 7 - 22  - f16c62c0cdea9bdb9b341227845a90516e8417eba2bc - The 22 byte array
These extra bytes (`7c6cff39cd12120e212106e05aeca6ee2f40126a3edcf015a4a4bc9932aed7fef1257c114265184f0e1833b7c2b9be2656b0833f7060d7301d250c1041e1d949c3651f8fc74e25c90c00000000000000004f00000000000000`) are causing issues.  
```
Calling chain_getBlock from within polkadot-js gives errors such as `Struct: failed on 'logs':: Bytes: required length less than remainder, expected at least 331575618, found 112`  I believe this error is due to incorrect data in this digest log.

## Possible Solution

- Unknown, but this is probably related to the current runtime.

## Steps to Reproduce

1. RPC call chain_getHeader and examine logs for digest type starting with 0x06

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by dutterbutter** [comment] 2020-12-18 17:14
@edwardmack please review to see if the issue is still relevant.

**Comment by noot** [comment] 2021-01-26 01:57
closing since it is no longer relevant

**Closed by noot** 2021-01-26 01:57 UTC
Labels: Priority: 3 - Medium, Type: Bug, approved
