### ISSUE TITLE
Digest Handler Doesn't Account for Forks with Different GRANDPA Messages

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2309] opened 2022-02-17 21:18 UTC
Similar to #2269. GRANDPA changes are not undone if there's a fork. This could cause consensus issues for functions like `handleScheduledChange()` and `handleForcedChange()` and `handleGrandpaChangesOnImport()` if different changes are scheduled in the forks then we will either error or return `nil` for the second block that is processed. In Substrate they use a `ForkTree` for the schedule changes and a `Vec` for the forced changes as seen in this struct from `substrate/client/finality-grandpa/src/authorities.rs`. There is another edge case that when there are multiple digest messages in a block, one with a scheduled change and the other with a forced change. In [Substrate](https://github.com/paritytech/substrate/blob/fb08d15bcbea68415dd4ee90d11556b653096f10/client/finality-grandpa/src/import.rs#L239) they will only process the forced change and ignore the rest. However in  Gossamer both the scheduled change and forced change will be processed.

**Comment by noot** [comment] 2022-03-17 19:21
duplicate of #2348

**Comment by danforbes** [comment] 2022-03-18 20:02
@noot this is not a duplicate, it is the Epic under which #2348 falls...I know this wasn't super clear given the descriptions, mainly because I was lazy when I created them and just copied-and-pasted 😅 Reopening this for now 👍🏻

**Comment by jimjbrettj** [comment] 2023-11-17 15:44
stale issue

**Closed by jimjbrettj** 2023-11-17 15:44 UTC
Labels: Type: Bug, W3F Approved, Epic
