### ISSUE TITLE
Add caching for tries in StorageState.

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1196] opened 2020-11-26 02:56 UTC
## Expected Behavior

- Tries should be stored and fetched from DB and deleted from the map since it will grow overtime. 

## Current Behavior

- Currently, we do store the tries in DB but don't delete it from the map. 

## Possible Solution

- Delete the trie form map and fetch it from DB.
- Since doing the above may take a performance hit, we can add a caching layer before DB.
- Our access pattern is predictable, we would need the most recent state tries. We can cache them.
- Caching library: https://github.com/dgraph-io/ristretto

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment] 2021-01-21 17:03
duplicate of #1321

**Closed by noot** 2021-01-21 17:03 UTC
Labels: Priority: 3 - Medium, Type: Maintenance, state
