### ISSUE TITLE
Research GRANDPA Consensus

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#75] opened 2019-03-22 18:30 UTC
Understand the mechanics of consensus

**Comment by noot** [comment] 2019-03-26 22:14
duplicate of #3 ?

**Comment by ansermino** [comment] 2019-03-28 19:55
@ChainSafe this is a sprint task, this other is a long term research task. This is on our sprint board the other is not. Please be more cautions before closing tasks.

**Closed** 2019-07-02 21:10 UTC
Labels: Backlog
