### ISSUE TITLE
Gossamer Devnet 

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#592] opened 2020-02-05 23:52 UTC
Gossamer devnet test cases outlined below:

| Test Case                  | Status      | What                                                                  | How                                                                                                    | Expected behaviour                                                                             |
|----------------------------|-------------|-----------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|
| Authority Nodes            | Ongoing     | Establish specific authority nodes and non-authority nodes            | 6 authority nodes configured, and check if they are rotating correctly, and producing/authoring blocks | Blocks produced and finalized over a long period of time                                       |
| Shut down authority nodes  | Ongoing     | Auth node finality                                                    | Shut down auth nodes in varying supply                                                                 | 6 auth and 1 goes down should continue, but if more than 2/3 rds go down finality should cease |
| Adding new authority nodes | Ongoing     | Ability to test new auth nodes with an ongoing chain                  | Add auth node after x blocks                                                                           | Added to auth node group, produce/author blocks                                                |
| Runtime upgrades           | Ongoing     | Ability to do runtime upgrades with gossamer nodes                    | Submit extrinsic indicating a runtime upgrade                                                          | Nodes runtime should be upgraded                                                               |
| Syncing                    | Not started | Ensure non-authority nodes are able to sync properly                  | Adding non-authority nodes at various block heights                                                    | Non-authority nodes will be able to sync properly                                              |
| Tooling checks             | Not started | Ensure rpc calls are available and accurate, and telemetry connection | Submit various rpc calls and ensure telemetry connection is correct                                    | Calls should go through and be accurate                                                        |
| Key management             | Not started | Ensure auth node key work correctly for staking and signing           | Utilize keys to stake and sign blocks                                                                  | Should not result in an error and correctly stakes / sign the block                            |
| Metrics and monitoring     | Not started | Monitor network traffic (gossip), and metrics gathering               | Configure grafana to capture metrics                                                                   |                                                                                                |

**Comment by noot** [comment] 2021-02-05 03:30
duplicate of #1356

**Comment by P1sar** [comment] 2024-03-14 14:08
Stale

**Closed by P1sar** 2024-03-14 14:08 UTC
