### ISSUE TITLE
Black Box tests for Candidate Backing

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3744] opened 2024-02-08 16:02 UTC
## Issue summary
The purpose of writing black box tests is to be able to figure out if a subsystem is working as expected without understanding it thoroughly. Anyone who wants to check if a subsystem works well, just needs to know what kind of messages this subsystem is supposed to receive and how should it respond to them.

So, we will mock the behavior of overseer.
We are going to test the behaviour of a subsystem checking how it reacts on receive a particular message from overseer. 

In particular for Candidate Backing, send following messages to overseer and see if it send appropriate messages back to overseer
-  backing.GetBackedCandidatesMessage 
- backing.CanSecondMessage
Check if its response channel receives right true or false value for different values of CanSecondMessage.
Check if a `ProspectiveParachainsMessageGetHypotheticalFrontier` message is being sent eventually.
- backing.SecondMessage
- backing.StatementMessage

## Other information and links

-

**Comment by timwu20** [comment] 2024-07-04 14:20
This seems like a duplicate of #4002

**Comment by P1sar** [comment] 2024-07-08 15:36
duplicated by #4002

**Closed by P1sar** 2024-07-08 15:36 UTC
Labels: S-subsystems-backing
