### ISSUE TITLE
ext_storage_changes_root [Runtime Imported Function]

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#190] opened 2019-07-15 20:15 UTC
There is a stub for this imported function in runtime/wasm.go. 

It is yet to be specced, see section E.1.9 in the spec (https://github.com/w3f/polkadot-re-spec/blob/master/polkadot_re_spec.pdf)

**Comment by noot** [comment] 2019-09-10 15:57
I don't think this exists in v0.4 or v0.5, so I'm going to close this for now

**Comment by noot** [comment] 2020-10-01 19:56
duplicate of #905

**Closed by noot** 2020-10-01 19:56 UTC
Labels: Priority: 3 - Medium, Status: BLOCKED, wasm
