### ISSUE TITLE
Scale unmarshalling error

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#1726] opened 2021-08-12 03:09 UTC
## Describe the bug
- I am facing the following problem while trying to transfer some value between accounts.

```
WARN[08-11|15:47:06] failed to apply extrinsic pkg=babe error="unmarshal error: EOF, field: <nil>" extrinsic="[57 2 ... 238]" caller=build.go:254
```

- Then, for testing, I have changed my branch to commit `ca99fbf1938c9de3f52f06c6bc2ca7a68efa3e89` (git checkout `ca99fbf1938c9de3f52f06c6bc2ca7a68efa3e89`) then started the node and the transfer functionality works.

- The complete extrinsic byte array is:
`57 2 132 0 212 53 147 199 21 253 211 28 97 20 26 189 4 169 159 214 130 44 133 88 133 76 205 227 154 86 132 231 165 109 162 125 1 108 111 48 166 52 247 42 230 42 219 33 35 87 186 33 217 103 57 165 106 28 7 124 73 21 101 57 255 74 204 34 15 10 179 178 3 39 160 210 126 249 152 128 161 152 161 26 79 212 42 251 123 161 245 251 246 78 255 189 21 158 104 142 138 22 1 0 0 6 3 0 212 97 51 42 52 46 217 216 139 242 232 28 174 94 156 153 136 191 126 154 255 28 22 196 33 71 191 0 231 253 158 109 2 40 107 238`

## Expected Behavior

- The scale package should be able to unmarshal the data from a runtime

## Current Behavior

- `error="unmarshal error: EOF, field: <nil>"`

## Possible Solution

- N/A

## To Reproduce
Steps to reproduce the behaviour:

1. On branch `development` starts a node with: `./bin/gossamer --chain gssmr --ws --rpc --key alice`
2. Then setup the polkadot explorer to connect with the node and executes a transfer between two accounts
3. The error log will appear in the node logs instantaneously.

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
</br>

## Specification

- go version: 1.15
- gossamer version: development
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by timwu20** [comment] 2021-08-13 18:44
I was unable to reproduce the issue on the `gssmr` or `dev` chains on my local using  polkadot apps v0.88.1 using latest commit on development.  Hopped on a call with @EclesioMeloJunior and was unable to reproduce the issue as well.  We are seeing successful account balance transfers between accounts based on the genesis accounts.  Going to close this issue.

**Closed by timwu20** 2021-08-13 18:44 UTC
Labels: Type: Bug, scale, p2
