### ISSUE TITLE
testing tear down optimization - cleanup optimization

### ISSUE THREAD

**Issue by thomasmodeneis** [ChainSafe/gossamer#803] opened 2020-04-22 17:08 UTC
## Expected Behavior

-

## Current Behavior

-

## Possible Solution

-

## Steps to Reproduce

1.
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [ ] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [ ] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by ryanchristo** [comment] 2020-05-07 21:16
@thomasmodeneis could you help fill this issue out more?

**Comment by ryanchristo** [comment] 2020-05-07 21:16
is this a duplicate of #800?

**Comment by noot** [comment] 2020-05-28 19:25
can we close this due to lack of information?

**Comment by ryanchristo** [comment] 2020-05-29 03:08
duplicate of #800

**Closed by ryanchristo** 2020-05-29 03:08 UTC
Labels: Priority: 3 - Medium, tests
