### ISSUE TITLE
Implement missing ext_crypto_ecdsa_generate_version_1 function

### ISSUE THREAD

**Issue by jimjbrettj** [ChainSafe/gossamer#3769] opened 2024-02-22 21:26 UTC
## Issue summary

- Implement the ext_crypto_ecdsa_generate_version_1 host function

## Other information and links

- https://spec.polkadot.network/chap-host-api#id-ext_crypto_ecdsa_generate

**Comment by axaysagathiya** [comment] 2024-04-29 04:16
Closing this as it's a duplicate of #2951. Which is already implemented by #3801 and https://github.com/ChainSafe/polkadot-spec/pull/14

**Closed by axaysagathiya** 2024-04-29 04:16 UTC
Labels: C-simple, T-feat
